#ifndef GAFFERBINDINGS_COMPOUNDNUMERICPLUGBINDING_H
#define GAFFERBINDINGS_COMPOUNDNUMERICPLUGBINDING_H

namespace GafferBindings
{

void bindCompoundNumericPlug();

} // namespace GafferBindings

#endif // GAFFERBINDINGS_COMPOUNDNUMERICPLUGBINDING_H
