#ifndef GAFFERUIBINDINGS_GRAPHGADGETBINDING_H
#define GAFFERUIBINDINGS_GRAPHGADGETBINDING_H

namespace GafferUIBindings
{

void bindGraphGadget();

} // namespace GafferUIBindings

#endif // GAFFERUIBINDINGS_GRAPHGADGETBINDING_H
