#ifndef GAFFERUIBINDINGS_SPLINEPLUGGADGETBINDING_H
#define GAFFERUIBINDINGS_SPLINEPLUGGADGETBINDING_H

namespace GafferUIBindings
{

void bindSplinePlugGadget();

} // namespace GafferUIBindings

#endif // GAFFERUIBINDINGS_SPLINEPLUGGADGETBINDING_H
